### ISSUE TITLE
Event API Call for Page 1

### ISSUE THREAD

**Issue by arrozconpollo220** [arrozconpollo220/SLC-Events#5]
- [x] Fetch request to ticketmaster.com for event data
- [x] Filter the request based on user input
- [x] Send data to a function that will populate data to page one. 

Acceptance Criteria
As a user, it is done when the appropriate data retrieved from ticketmaster.com

**Comment by orian42** [comment]
Pushed some code to GitHub.  Waiting for modal to finish the code.
