### ISSUE TITLE
Display list of events to page 1

### ISSUE THREAD

**Issue by arrozconpollo220** [arrozconpollo220/SLC-Events#6]
- [x] Receive information from the event API function
- [x] Create link for each event 
- [x] Each link should have a date and title of the event
- [x] Link will redirect to page 2 with single event information saved to local storage. (info will be recalled on page 2)

Acceptance Criteria
As a user, it is done when I can see my list of events on page 1 and When I click on an event, I will be taken to page 2 and the event information will be stored in local storage.

**Comment by orian42** [comment]
Single event details saved to local storage
